### PR TITLE
Added global error handling and status indicator

### LINKED ISSUE #104: Deal with stack size limit exceptions
## Details:
Hours Spent: 8

## Background
Occasionally we get a silent failure with "stack size limit exceeded" exception showing on the JS console.

## Overview
Investigate what is responsible for this exception and try to fix it or at least detect it. 

## Acceptance Criteria
- [x] There are no exceptions or exceptions are reported on a range of stress tests.

## Closing Notes

Overview of changes can be found in PR _PR ID HERE_

### LINKED ISSUE #123: Status indicator
## Details:
Hours Spent: 1

## Overview
There should be a text and colour-based status indicator, possibly near or on the current progress bar.

## Acceptance Criteria
- [x] Show status changes: ready, some enclosures not computed, segmenting, computing robust enclosure, internal error.
- [x] On error status, make the status indicator show in red.

## Closing Notes

Overview of changes can be found in PR _PR ID HERE_

### PR DESCRIPTION
**Pull request by RelativeForce**
# Issues
closes #104 
closes #123 

# Summary of changes
- Added `handleError` function for handling when an error is thrown by a function, It uses a continuation function if there is no error thrown.
- Replaced `lift $ lift` with `H.liftAff`
- Added `clearGlobalError` for removing the error from the state.
- Moved `clearAddPlotCommands` and `fromPixelAccuracy` from `Plot.Helper` into `Plot.Action`
- Added the error to the state 
- Added status indicator

# Tests
N/A

### CODE REVIEW

**Comment by michalkonecny** [comment]
The status badge is nice.  I think it should be moved nearer the canvas, to the right of the "Reset bounds" button, still flushed to the right edge.

**Comment by michalkonecny** [comment]
The bug I mentioned this morning still needs addressing: The progress bar and the enclosure are showing with one batch delay. Also, when the status says "segmenting", it is actually already computing the first batch according to the console log messages.

**Comment by michalkonecny** [comment]
The other bug too: When changing the accuracy target, robust computation is triggered but the spinner does not come on until the first batch has been computed.

**Comment by RelativeForce** [comment]
All changes have been made. PR ready for approval

**Review by michalkonecny — APPROVED** [review]
All good, thank you!

**Pull request merged**
